# This is a config for E2B sandbox template.
# You can use template ID (e7iat1qlfbulpw070973) or template name (lovable-nextjs-v15) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lovable-nextjs-v15") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-nextjs-v15") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-nextjs-v15')

team_id = "ff8eb560-6b89-4e83-94bd-41d194ccf181"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-nextjs-v15"
template_id = "e7iat1qlfbulpw070973"
