# This is a config for E2B sandbox template.
# You can use template ID (u66ic5njhoer796d9c2z) or template name (vibe-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs')

team_id = "ff8eb560-6b89-4e83-94bd-41d194ccf181"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs"
template_id = "u66ic5njhoer796d9c2z"
